#!/bin/bash

tmp=/tmp/p-basic.tmp

cmd='echo -n "Hello " > ${tmp}'
echo "+ ${cmd}"
eval "${cmd}"

echo

( set -x ; scripts/python -m logtool.pscript --quiet --append --command "echo World" ${tmp} )

echo ; echo "= = = = =" ; echo

( set -x ; cat ${tmp} )

rm -f ${tmp}

echo

